#! .venv/bin/python3
"""Learn: Restyle — iterative improvement loop for the restyle (IP-Adapter) pipeline.

Pipeline flow: source avatar + target style → ipadapter_faceid → scored candidate.

For each iteration:
  1. Sample examples (--samples / --range / full set)
  2. For each example, call restyle_avatar() to generate a restyled image
  3. Score: identity preservation (compare_side_by_side) + style match (classify_image_style)
  4. Analyze failures, ask reasoning LLM for fixes (style directives, IP-Adapter weight, prompts)
  5. Repeat with worst-half + fresh examples until plateau or max-iterations

The source image for each example is taken from assets/examples/<name>/photorealistic.png
(the reference photorealistic avatar generated by the create pipeline).

Usage:
    python scripts/learn/learn_restyle.py --samples 20
    python scripts/learn/learn_restyle.py --range 0 49 --max-iterations 5 --optimize fast
    python scripts/learn/learn_restyle.py  # full set — prompts for confirmation
"""

from __future__ import annotations

import argparse
import base64
import json
import logging
import subprocess
import sys
import textwrap
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path

import yaml

# ── project root on sys.path ──────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts" / "examples"))

from _cli import add_common_args, confirm_full_set  # noqa: E402
from _example_utils import EXAMPLES_DIR, REPORTS_DIR, load_all_personas  # noqa: E402
from _logger import make_logger  # noqa: E402
from _sampler import initial_sample, iteration_schedule, next_sample  # noqa: E402

from config.gateway import GatewayClient  # noqa: E402
from pipeline.render.llm.prompt_builder import build_prompt  # noqa: E402
from pipeline.render.style_resolver import resolve_style  # noqa: E402
from tuning.classify_style import classify_image_style  # noqa: E402
from tuning.compare_side_by_side import compare_side_by_side  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

STYLES_YML = ROOT / "assets" / "styles" / "styles.yml"
STYLE_PASS_THRESHOLD = 0.66
IDENTITY_PASS_THRESHOLD = 0.60
PLATEAU_DELTA = 0.01
PLATEAU_PATIENCE = 2

_NEUTRAL_EXPR = {
    "expression": "Neutral",
    "facs_action_units": "",
    "description": "Resting face, relaxed muscles, eyes looking directly forward, mouth closed.",
}

_FIX_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "style_prompt_patches": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "style_id": {"type": "string"},
                    "find": {"type": "string"},
                    "replace": {"type": "string"},
                },
                "required": ["style_id", "find", "replace"],
                "additionalProperties": False,
            },
        },
        "weight_suggestion": {"type": "number"},
        "rationale": {"type": "string"},
    },
    "required": ["style_prompt_patches", "weight_suggestion", "rationale"],
    "additionalProperties": False,
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_styles() -> list[dict]:
    with open(STYLES_YML) as f:
        data = yaml.safe_load(f)
    return [s for s in data["styles"] if s.get("engine") == "llm" and s.get("id") != "random"]


def _atomic_write(path: Path, data: dict) -> None:
    tmp = path.with_suffix(".tmp")
    with open(tmp, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    tmp.rename(path)


def _check_plateau(score_history: list[float]) -> bool:
    if len(score_history) < PLATEAU_PATIENCE + 1:
        return False
    deltas = [
        abs(score_history[-i] - score_history[-i - 1]) for i in range(1, PLATEAU_PATIENCE + 1)
    ]
    return all(d < PLATEAU_DELTA for d in deltas)


def _source_image(example_dir: Path) -> bytes | None:
    """Return bytes of the source avatar image for restyle input, or None if missing."""
    for fname in ("photorealistic.png", "photorealistic_benchmark_1.png"):
        p = example_dir / fname
        if p.exists():
            with open(p, "rb") as f:
                return f.read()
    return None


# ---------------------------------------------------------------------------
# Generate + score one example
# ---------------------------------------------------------------------------


def _process_one(
    client: GatewayClient,
    name: str,
    style_entry: dict,
    example_dir: Path,
    all_styles: list[dict],
    *,
    optimize: str,
) -> dict:
    style_id = style_entry["id"]
    result: dict = {"example": name, "style_id": style_id, "error": None}

    source_bytes = _source_image(example_dir)
    if source_bytes is None:
        result["error"] = "no source image"
        return result

    source_b64 = base64.b64encode(source_bytes).decode()
    _, style_directive = resolve_style(style_id)
    prompt = build_prompt({}, _NEUTRAL_EXPR, style_directive, reference_mode="style_transfer")

    # Generate via IP-Adapter
    t0 = time.time()
    try:
        candidate_bytes = client.ipadapter_faceid(
            prompt,
            [source_b64],
            width=512,
            height=512,
            optimize=optimize,
        )
    except Exception as exc:
        result["error"] = f"generation: {exc}"
        return result
    result["generation_time_s"] = round(time.time() - t0, 1)

    # Score: style match
    try:
        style_result = classify_image_style(
            candidate_bytes, all_styles, gateway_url=client.base_url
        )
        style_score = style_result.scores.get(style_id, 0.0)
        if style_result.top_style_id == style_id and style_score == 0.0:
            style_score = STYLE_PASS_THRESHOLD
        result["style_score"] = round(style_score, 3)
    except Exception as exc:
        logger.warning("style classification failed %s: %s", name, exc)
        result["style_score"] = 0.0

    # Score: identity (SBS)
    try:
        sbs = compare_side_by_side(
            source_bytes,
            candidate_bytes,
            goal="Re-render the avatar in a new style while preserving identity.",
            reference_label="source",
            generated_label="restyled",
            gateway_url=client.base_url,
        )
        result["identity_score"] = round(sbs.identity_score, 3)
        result["compound_score"] = round(sbs.compound_score, 3)
        result["sbs_reasoning"] = (sbs.reasoning or "")[:200]
    except Exception as exc:
        logger.warning("SBS failed %s: %s", name, exc)
        result["identity_score"] = 0.0
        result["compound_score"] = 0.0

    return result


# ---------------------------------------------------------------------------
# LLM fix for restyle
# ---------------------------------------------------------------------------


def _apply_restyle_fixes(
    client: GatewayClient,
    entries: list[dict],
    fixes_path: Path,
    component_threshold: float = 0.75,
) -> dict:
    """Ask reasoning LLM for restyle improvements, apply style prompt patches."""
    failures = [
        e
        for e in entries
        if not e.get("error")
        and (
            e.get("style_score", 0) < component_threshold
            or e.get("identity_score", 0) < component_threshold
        )
    ]

    failure_summary = "\n".join(
        f"  {e['example']} x {e['style_id']}: "
        f"style={e.get('style_score', 0):.0%}  identity={e.get('identity_score', 0):.0%}  "
        f'"{e.get("sbs_reasoning", "")[:100]}"'
        for e in failures[:20]
    )

    with open(STYLES_YML) as f:
        styles_content = f.read()

    reasoning_prompt = textwrap.dedent(f"""
        You are improving the avatar-studio restyle pipeline (IP-Adapter FaceID based).
        The restyle pipeline re-renders an existing avatar in a new style using IP-Adapter.

        ## Failures (style score < {component_threshold:.0%} or identity score < {component_threshold:.0%})
        {failure_summary or "(none)"}

        ## Current styles.yml
        {styles_content}

        Analyze the failures:
        1. Which styles are consistently failing style classification?
        2. Which examples are losing identity (low identity score)?
        3. What changes to the style system_prompt would help?
        4. What IP-Adapter weight (0.0–1.0) would better balance identity vs style?

        Be specific and reference exact strings from styles.yml.
    """).strip()

    schema_json = json.dumps(_FIX_SCHEMA, indent=2)
    format_prompt = textwrap.dedent(f"""
        Based on the analysis below, produce a JSON fix specification.

        ANALYSIS:
        {{reasoning}}

        OUTPUT SCHEMA (single valid JSON object, no prose):
        {schema_json}

        Rules:
        - style_prompt_patches: patches to system_prompt strings in styles.yml
        - weight_suggestion: new IP-Adapter weight (0.0 = full style, 1.0 = full identity);
          use null if no change needed
        - Leave arrays empty if no changes needed.
    """).strip()

    applied: list[str] = []
    skipped: list[str] = []
    fixes: dict = {"style_prompt_patches": [], "weight_suggestion": None, "rationale": ""}

    try:
        reasoning_output = client.reasoning(
            messages=[{"role": "user", "content": reasoning_prompt}], timeout=600
        )
    except Exception as exc:
        logger.error("Reasoning model failed: %s", exc)
        fixes["_error"] = str(exc)
        fixes["_applied"] = applied
        fixes["_skipped"] = skipped
        _atomic_write(fixes_path, fixes)
        return fixes

    try:
        raw = client.general(
            messages=[
                {"role": "user", "content": format_prompt.replace("{reasoning}", reasoning_output)}
            ],
            timeout=120,
        )
        import re

        text = raw.strip()
        fence = re.search(r"```(?:json)?\s*([\s\S]*?)```", text)
        if fence:
            text = fence.group(1).strip()
        fixes = json.loads(text)
    except Exception as exc:
        logger.error("Format model failed: %s", exc)
        fixes["_error"] = str(exc)
        fixes["_applied"] = applied
        fixes["_skipped"] = skipped
        _atomic_write(fixes_path, fixes)
        return fixes

    fixes["_reasoning"] = reasoning_output[:2000]

    # Apply style prompt patches
    with open(STYLES_YML) as f:
        styles_text = f.read()
    original = styles_text
    for patch in fixes.get("style_prompt_patches", []):
        find_str = patch.get("find", "")
        replace_str = patch.get("replace", "")
        if not find_str:
            skipped.append(f"empty find string for style {patch.get('style_id')}")
            continue
        if find_str not in styles_text:
            skipped.append(f"find string not found in styles.yml for {patch.get('style_id')}")
            continue
        styles_text = styles_text.replace(find_str, replace_str, 1)
        applied.append(f"styles.yml patch: {patch.get('style_id')}")
    if styles_text != original:
        tmp = STYLES_YML.with_suffix(".tmp")
        tmp.write_text(styles_text)
        tmp.rename(STYLES_YML)

    fixes["_applied"] = applied
    fixes["_skipped"] = skipped
    _atomic_write(fixes_path, fixes)

    logger.info("Restyle fixes applied: %d  Skipped: %d", len(applied), len(skipped))
    return fixes


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------


def run_learn_restyle(
    *,
    max_iterations: int,
    stop_on_plateau: bool,
    gateway_url: str,
    examples_dir: Path,
    workers: int,
    optimize: str,
    log_dir: Path,
    samples: int | None,
    range_: tuple[int, int] | None,
    style_filter: list[str] | None = None,
    component_threshold: float = 0.75,
    compound_threshold: float = 0.90,
) -> None:
    log = make_logger("learn_restyle", log_dir)

    all_examples = load_all_personas(examples_dir)
    # Filter to examples that have a source avatar image
    all_examples = [(n, p) for n, p in all_examples if _source_image(examples_dir / n) is not None]
    if not all_examples:
        logger.error("No examples with source avatar image found in %s", examples_dir)
        sys.exit(1)

    if samples is None and range_ is None:
        confirm_full_set(len(all_examples))

    current_sample = initial_sample(all_examples, n=samples, range_=range_)
    target_n = len(current_sample)
    schedule = iteration_schedule(target_n, max_n=512, max_iterations=max_iterations)

    ts = datetime.now().strftime("%y-%m-%d-%H-%M")
    loop_dir = REPORTS_DIR / f"learn_restyle_{ts}"
    loop_dir.mkdir(parents=True, exist_ok=True)

    all_styles = _load_styles()

    if style_filter:
        known_ids = {s["id"] for s in all_styles}
        unknown = [sid for sid in style_filter if sid not in known_ids]
        if unknown:
            logger.error("Unknown style(s): %s  (available: %s)", unknown, sorted(known_ids))
            sys.exit(1)
        all_styles = [s for s in all_styles if s["id"] in style_filter]

    log.config(
        script="learn_restyle",
        max_iterations=max_iterations,
        stop_on_plateau=stop_on_plateau,
        workers=workers,
        optimize=optimize,
        samples=target_n,
        styles=[s["id"] for s in all_styles],
        loop_dir=str(loop_dir),
    )

    logger.info(
        "learn_restyle: samples=%d  max_iter=%d  optimize=%s", target_n, max_iterations, optimize
    )

    client = GatewayClient(gateway_url)
    score_history: list[float] = []
    state: dict = {"loop_dir": str(loop_dir), "iterations": []}

    for iteration in range(1, max_iterations + 1):
        prefix = f"iter_{iteration:02d}"
        sample_names = {name for name, _ in current_sample}

        # Generate + score all (example, style) pairs
        work = [
            (name, persona, style_entry)
            for name, persona in current_sample
            for style_entry in all_styles
            if sample_names  # always true, just to use the variable
        ]
        entries: list[dict] = []

        logger.info("[iter %d/%d] Generating %d images…", iteration, max_iterations, len(work))

        if workers <= 1:
            for name, persona, style_entry in work:
                entry = _process_one(
                    client, name, style_entry, examples_dir / name, all_styles, optimize=optimize
                )
                entries.append(entry)
                log.render(
                    iteration=iteration,
                    example=name,
                    style=style_entry["id"],
                    error=entry.get("error"),
                )
                if not entry.get("error"):
                    log.score(
                        iteration=iteration,
                        example=name,
                        style=style_entry["id"],
                        style_score=entry.get("style_score"),
                        identity_score=entry.get("identity_score"),
                    )
        else:
            with ThreadPoolExecutor(max_workers=workers) as pool:
                futures = {
                    pool.submit(
                        _process_one,
                        client,
                        name,
                        style_entry,
                        examples_dir / name,
                        all_styles,
                        optimize=optimize,
                    ): (name, style_entry["id"])
                    for name, persona, style_entry in work
                }
                for future in as_completed(futures):
                    name, style_id = futures[future]
                    try:
                        entry = future.result()
                    except Exception as exc:
                        entry = {"example": name, "style_id": style_id, "error": str(exc)}
                    entries.append(entry)
                    log.render(
                        iteration=iteration, example=name, style=style_id, error=entry.get("error")
                    )
                    if not entry.get("error"):
                        log.score(
                            iteration=iteration,
                            example=name,
                            style=style_id,
                            style_score=entry.get("style_score"),
                            identity_score=entry.get("identity_score"),
                        )

        # Summarize
        successful = [e for e in entries if not e.get("error")]
        avg_style = (
            sum(e.get("style_score", 0) for e in successful) / len(successful)
            if successful
            else 0.0
        )
        avg_identity = (
            sum(e.get("identity_score", 0) for e in successful) / len(successful)
            if successful
            else 0.0
        )
        combined = (avg_style + avg_identity) / 2
        score_history.append(combined)

        log.summary(
            iteration=iteration,
            avg_style=round(avg_style, 3),
            avg_identity=round(avg_identity, 3),
            combined=round(combined, 3),
            n_successful=len(successful),
            n_failed=len(entries) - len(successful),
        )
        logger.info(
            "[iter %d] style=%.0f%%  identity=%.0f%%  combined=%.0f%%",
            iteration,
            avg_style * 100,
            avg_identity * 100,
            combined * 100,
        )

        # Plateau check
        if stop_on_plateau and _check_plateau(score_history):
            logger.info("Plateau detected — stopping")
            log.plateau(iteration=iteration, score_history=score_history)
            log.done(reason="plateau", iteration=iteration)
            state["iterations"].append(
                {"iter": iteration, "combined": combined, "status": "PLATEAU_STOP"}
            )
            _atomic_write(loop_dir / "state.json", state)
            break

        # LLM fixes
        fixes_path = loop_dir / f"{prefix}_fixes.json"
        fixes = _apply_restyle_fixes(
            client, entries, fixes_path, component_threshold=component_threshold
        )
        for fix_desc in fixes.get("_applied", []):
            log.fix(iteration=iteration, description=fix_desc)

        state["iterations"].append(
            {
                "iter": iteration,
                "avg_style": round(avg_style, 3),
                "avg_identity": round(avg_identity, 3),
                "fixes_applied": len(fixes.get("_applied", [])),
                "status": "IMPROVING",
            }
        )
        _atomic_write(loop_dir / "state.json", state)

        # Next sample
        if iteration < max_iterations:
            example_scores = {e["example"]: e.get("identity_score", 0.0) for e in successful}
            prev_scored = [(ex, example_scores.get(name, 0.0)) for name, ex in current_sample]
            next_target = schedule[iteration]
            current_sample = next_sample(
                all_examples, prev_scored=prev_scored, target_n=next_target
            )

    else:
        logger.info("Reached max iterations (%d).", max_iterations)
        log.done(reason="max_iterations", iterations=max_iterations)

    print(f"\n{'=' * 60}")
    print(f"learn_restyle complete — {len(state['iterations'])} iterations")
    print(f"State: {loop_dir / 'state.json'}")
    print(f"Log:   {log._path}")

    diff = subprocess.run(
        ["git", "diff", "--stat", "assets/"], capture_output=True, text=True, cwd=ROOT
    )
    if diff.stdout.strip():
        print("\n--- git diff --stat (assets/) ---")
        print(diff.stdout.strip())


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Learn: iterative improvement for the restyle (IP-Adapter) pipeline"
    )
    add_common_args(parser)
    parser.add_argument("--examples-dir", type=Path, default=EXAMPLES_DIR)
    parser.add_argument(
        "--style",
        nargs="+",
        default=["all"],
        metavar="STYLE",
        help="Style ID(s) to run, or 'all' (default: all)",
    )
    args = parser.parse_args()

    style_filter = None if args.style == ["all"] else args.style

    run_learn_restyle(
        max_iterations=args.max_iterations,
        stop_on_plateau=args.stop_on_plateau,
        gateway_url=args.gateway,
        examples_dir=args.examples_dir,
        workers=args.workers,
        optimize=args.optimize,
        log_dir=args.log_dir,
        samples=args.samples,
        range_=tuple(args.range) if args.range else None,
        style_filter=style_filter,
        component_threshold=args.component_threshold / 100,
        compound_threshold=args.compound_threshold / 100,
    )
